/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: efb27ae42ac6118aa81d1a98876e2cd7)
interface __BaseEnv_Env {
	BOOKING_EMAIL: SendEmail;
	BOOKING_FROM_EMAIL: "website@sidelineaction.be";
	BOOKING_TO_EMAIL: "harunviteskic50@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BOOKING_FROM_EMAIL" | "BOOKING_TO_EMAIL">> {}
}
